# 获取所有设备
GET http://{{hostname}}/device/?password={{password}}
Authorization: {{token}}
Accept: application/json

###

# 根据范围获取所有设备
GET http://{{hostname}}/device/?start=0&end=10&password={{password}}
Authorization: {{token}}
Accept: application/json

###

# 添加第一台设备
POST http://{{hostname}}/device/?password={{password}}
Content-Type: application/json

{
  "name": "安卓",
  "type": 1
}

###

# 添加第二台设备
POST http://{{hostname}}/device/?password={{password}}
Content-Type: application/json

{
  "name": "安卓1",
  "type": 2
}

###

# 添加重复设备
POST http://{{hostname}}/device/?password={{password}}
Content-Type: application/json

{
  "name": "安卓",
  "type": 1
}

###

# 查询存在设备
GET http://{{hostname}}/device/安卓/?password={{password}}
Authorization: {{token}}
Accept: application/json

###
# 查询不存在设备
GET http://{{hostname}}/device/安卓0/?password={{password}}
Authorization: {{token}}
Accept: application/json

###

# 删除存在设备
DELETE http://{{hostname}}/device/安卓1/?password={{password}}
Authorization: {{token}}
Content-Type: application/json

###
# 删除不存在设备
DELETE http://{{hostname}}/device/安卓0/?password={{password}}
Authorization: {{token}}
Content-Type: application/json

###

# 更新存在设备
PUT http://{{hostname}}/device/安卓1/?password={{password}}
Authorization: {{token}}
Content-Type: application/json

{
  "Type": 1,
  "IsAdmin": false,
  "IsRead": true,
  "IsSend": true
}

###

# 更新不存在设备
PUT http://{{hostname}}/device/安卓0/?password={{password}}
Authorization: {{token}}
Content-Type: application/json

{
  "Type": 1,
  "IsAdmin": false,
  "IsRead": true,
  "IsSend": true
}

###